use_frameworks!

platform :ios, '8.0'

target 'oc-viper-base_Example' do
  pod 'oc-viper-base', :path => '../'

  target 'oc-viper-base_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
